<?php
$blog = $block->getBlog();
?>
<div class="blog-container">
    <form class="blog-form" method="post" action=<?= $escaper->escapeUrl($block->getUrl('blog/manage/save')); ?> data-mage-init='{"validation": {}}'>
    <input type="hidden" name="id" value="<?= $escaper->escapeHtml($blog->getId())?>"/>
    Title: <input type="text" name="title" class="required-entry" value="<?= $escaper->escapeHtml($blog->getTitle()); ?>"/>
    Content: <textarea name="content" class="required-entry validate-no-html-tags" rows="10"><?= $escaper->escapeHtml($blog->getContent()); ?></textarea>
    <button type="submit">Submit</button>
    </form>
</div>
