<table>
    <tr>
        <th>
            <?= __("Id")?>
        </th>
        <th>
            <?= __("Title")?>
        </th>
        <th>
            <?= __("Content")?>
        </th>
        <th>
            <?= __("Edit")?>
        </th>
        <th>
            <?= __("Delete")?>
        </th>
    </tr>
    <?php
    $blogs = $block->getBlogs();

    foreach ($blogs as $blog) {?>
        <tr>
            <td>
                <?= $escaper->escapeHtml($blog->getId())?>
            </td>
            <td>
                <?= $escaper->escapeHtml($blog->getTitle())?>
            </td>
            <td>
                <?= substr($escaper->escapeHtml($blog->getContent()), 0, 20).'...'?>
            </td>
            <td>
                <a href="<?= $escaper->escapeUrl($block->getUrl('blog/manage/edit', ['id'=>$escaper->escapeHtml($blog->getId())]))?>">
                    <?= __('Edit') ?>
                </a>
            </td>
            <td>
                <a href="<?= $escaper->escapeUrl($block->getUrl('blog/manage/delete', ['id'=>$escaper->escapeHtml($blog->getId())]))?>"
                   onclick="return confirm('Are you sure you want to delete this blog?');">
                    <?= __('Delete') ?>
                </a>
            </td>
        </tr>
    <?php } ?>
</table>
